# Generated by Django 3.1.4 on 2020-12-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20201229_1901'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='kirr_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shortener.kirrurl'),
        ),
    ]
